# Generated by Django 4.2.4 on 2023-09-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveducativos', '0002_niveducativo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Especificar', max_length=40)),
                ('apellido', models.CharField(default='Sin Especificar', max_length=40)),
                ('dni', models.BigIntegerField()),
                ('niveducativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='niveducativos.niveducativo')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
    ]
