# Generated by Django 4.2.4 on 2023-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='direccion',
            field=models.CharField(default='Sin Especificar', max_length=255),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
