# Generated by Django 4.2.4 on 2023-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_inscripcion_direccion_inscripcion_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='email',
            field=models.EmailField(default='Sin especificar', max_length=254),
        ),
    ]
