# Generated by Django 4.2.4 on 2023-09-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        ('comentarios', '0002_comentario_descripcion_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia'),
        ),
    ]
