# Generated by Django 4.2.4 on 2023-09-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rol_nombre'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.rol'),
        ),
    ]
