# Generated by Django 4.2.4 on 2023-09-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='usuarios/usuario-default.png', null=True, upload_to='usuarios'),
        ),
    ]
