# Generated by Django 4.2.4 on 2023-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
