# Generated by Django 4.2.4 on 2023-09-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='portada',
            field=models.ImageField(blank=True, default='noticias/portada-default.jpg', null=True, upload_to='noticias'),
        ),
    ]
