# Generated by Django 4.2.4 on 2023-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Especificar', max_length=40)),
                ('apellido', models.CharField(default='Sin Especificar', max_length=40)),
                ('telefono', models.BigIntegerField(default='0')),
                ('email', models.EmailField(default='Sin Especificar', max_length=254)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'aspirante',
                'managed': True,
            },
        ),
    ]
